//USER STUFF
export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"
export const SET_API_KEYS = "SET_API_KEYS"
export const SET_APP_USER_LOCATION = "SET_APP_USER_LOCATION"
export const SET_APP_USER_COORDINATES = 'SET_APP_USER_COORDINATES'


//REPORTS STUFF
export const SET_REPORTS = "SET_REPORTS"


//LOCATION STUFF
export const RESET_LOCATION_IDS = "RESET_LOCATION_IDS"
export const SET_CURRENT_COUNTRY_ID = "SET_CURRENT_COUNTRY_ID"
export const SET_CURRENT_STATE_ID = "SET_CURRENT_STATE_ID"
export const SET_CURRENT_CITY_ID = "SET_CURRENT_CITY_ID"

export const SET_CURRENT_COUNTRY_CENTER = "SET_CURRENT_COUNTRY_CENTER"