//USER STUFF
export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"
export const SET_API_KEYS = "SET_API_KEYS"
export const SET_APP_USER_LOCATION = "SET_APP_USER_LOCATION"
export const SET_APP_USER_COORDINATES = 'SET_APP_USER_COORDINATES'


//REPORTS STUFF
export const SET_REPORTS = "SET_REPORTS"


//LOCATION STUFF
export const RESET_LOCATION_IDS = "RESET_LOCATION_IDS"
export const RESET_LOCATION_PARAMS = "RESET_LOCATION_PARAMS"
export const SET_CURRENT_COUNTRY_ID = "SET_CURRENT_COUNTRY_ID"
export const SET_CURRENT_STATE_ID = "SET_CURRENT_STATE_ID"
export const SET_CURRENT_CITY_ID = "SET_CURRENT_CITY_ID"
export const SET_CURRENT_COUNTRY_CENTER = "SET_CURRENT_COUNTRY_CENTER"
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY"
export const SET_USER_COUNTRY = "SET_USER_COUNTRY"

//VIEWS
export const RESET_VIEWS = "RESET_VIEWS"
export const SET_QUARANTINE_VIEW = "SET_QUARANTINE_VIEW"
export const SET_INFECTIONS_VIEW = "SET_INFECTIONS_VIEW"
export const SET_UPDATES_VIEW = "SET_UPDATES_VIEW"
export const SET_HELP_REQUESTS_VIEW = "SET_HELP_REQUESTS_VIEW"
export const SET_BARTERS_VIEW = "SET_BARTERS_VIEW"
export const SET_REPORT_INFECTIONS_VIEW = "SET_REPORT_INFECTIONS_VIEW"
export const SET_SIGNUP_VIEW = "SET_SIGNUP_VIEW"